/*
	Concatenates the CSS sources in src/styles into the styles.css file that
	Obsidian loads for this plugin. Run through `npm run build` or `npm run dev`.
*/

import { readFileSync, writeFileSync } from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE
if you want to view the source, please visit the github repository of this plugin
*/
`;

const sources = ['src/styles/garble.css', 'src/styles/fonts.css'];

const css = sources.map((file) => readFileSync(file, 'utf8').trim()).join('\n\n');

writeFileSync('styles.css', `${banner}\n${css}\n`);
